version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run: |
          echo "The branch is ${CIRCLE_BRANCH}"
          TELLFINDER_TAG=`echo "${CIRCLE_BRANCH//release\//}"`
      - run: |
          echo "The tellfinder build tag is ${TELLFINDER_TAG}"

workflows:
  version: 2
  run-the-build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /release\/.*/