version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Compute the TellFinder build tag from the branch
          command: |
            echo "The branch is ${CIRCLE_BRANCH}"
            TELLFINDER_TAG="latest"
            RELEASE_REGEX="release\/.*"

            if [[ ${CIRCLE_BRANCH} =~ ${RELEASE_REGEX} ]]; then
              TELLFINDER_TAG=${CIRCLE_BRANCH//release\//}
            fi

            echo "The tellfinder build tag is ${TELLFINDER_TAG}"
            echo "export TELLFINDER_TAG=${TELLFINDER_TAG}" >> $BASH_ENV
            source $BASH_ENV

      - run: |
          echo "The tellfinder build tag is ${TELLFINDER_TAG}"

workflows:
  version: 2
  run-the-build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /release\/.*/
