version: 2
jobs:
  build:
    docker:
      - image: uncharted/circleci:openjdk-8-jdk-nodejs
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Compute the TellFinder build tag from the branch
          command: |
            echo "The branch is ${CIRCLE_BRANCH}"
            TELLFINDER_TAG="latest"
            RELEASE_REGEX="^release\/.*"

            if [[ ${CIRCLE_BRANCH} =~ ${RELEASE_REGEX} ]]; then
              TELLFINDER_TAG=${CIRCLE_BRANCH//release\//}
            fi

            echo "The tellfinder build tag is ${TELLFINDER_TAG}"
            echo "export TELLFINDER_TAG=${TELLFINDER_TAG}" >> $BASH_ENV
            source $BASH_ENV

      - run: |
          echo "The tellfinder build tag is ${TELLFINDER_TAG}"

