version: 2
jobs:
  build:
    docker:
      - image: uncharted/circleci:openjdk-8-jdk-nodejs
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Compute the TellFinder build tag from the branch
          command: |
            echo "The branch is ${CIRCLE_BRANCH}"
            RELEASE_REGEX="^release\/.*"

            TELLFINDER_TAG="unpushed"
            if [[ ${CIRCLE_BRANCH} =~ ${RELEASE_REGEX} ]]; then
              TELLFINDER_TAG=${CIRCLE_BRANCH//release\//}
            elif [ ${CIRCLE_BRANCH} == "master" ]; then
              TELLFINDER_TAG="latest"
            fi

            echo "export TELLFINDER_TAG=${TELLFINDER_TAG}" >> $BASH_ENV
            source $BASH_ENV

      - run: |
          echo "The tellfinder build tag is ${TELLFINDER_TAG}"

workflows:
  version: 2
  run-the-build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /^release\/.*/
