# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:

    branches:
      only:
        - master
        - /release\/.*/

    docker:
      # built from the Dockerfile in this directory
      - image: uncharted/circleci:openjdk-8-jdk-nodejs

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - setup_remote_docker:
          version: 17.06.1-ce

      # build
      - run: |
          echo "Hello world!"

workflows:
  version: 2
  build:
    jobs:
      - build